export const SET_RINGCHARTDATA = "SET_RINGCHARTDATA"

export const SET_CITYAREAALARMDATA = "SET_CITYAREAALARMDATA"

export const SET_LINELOSSDATA = "SET_LINELOSSDATA"

export const SET_LOADRATEDATA = "SET_LOADRATEDATA"

export const SET_ELECTRICITYANALYSISDATA = "SET_ELECTRICITYANALYSISDATA"

export const SET_LOADANALYSISDATA = "SET_LOADANALYSISDATA"

export const SET_ELECTRICITYDATA = "SET_ELECTRICITYDATA"

export const SET_USERSPOWERDATA = "SET_USERSPOWERDATA"

export const REFRESHALL = "REFRESHALL"
